/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.Customer;
import model.Motorbike;
import model.RentLog;

/**
 *
 * @author phuct
 */
public class RentMotorbikePanel extends javax.swing.JPanel {

    /**
     * Creates new form MotorbikePanel
     */
    RentLog rentLog = new RentLog();

    public RentMotorbikePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        IDMotorbikeText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        IDnumText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DesText = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Rent Motorbike");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("Rent");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setLayout(new java.awt.GridLayout(3, 2));

        jLabel2.setText("ID Motorbiker");
        jPanel3.add(jLabel2);
        jPanel3.add(IDMotorbikeText);

        jLabel3.setText("ID Number");
        jPanel3.add(jLabel3);
        jPanel3.add(IDnumText);

        jLabel4.setText("Descriptor");
        jPanel3.add(jLabel4);
        jPanel3.add(DesText);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String idcus = IDnumText.getText();
        int idmt = 0; 
        try {
            idmt = Integer.parseInt(IDMotorbikeText.getText());
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid motorbike ID. Please enter a valid integer.");
        }

        String des = DesText.getText();

        Customer customer = MainGUI.shop.getCustomerByID(idcus);

        if (customer != null) {
            System.out.println("Found Customer: " + customer.getName());

            Motorbike rentedMotorbike = MainGUI.shop.rentMotorbikeforGUI(idmt, customer, des);

            if (rentedMotorbike != null) {
                System.out.println("Rented Motorbike: " + rentedMotorbike.getBrandName());
                JOptionPane.showMessageDialog(null, "Successfully rented the motorbike!");
                // Display rent bill using JOptionPane
                String billMessage = rentLog.displayBillRentforGUI();
//                JOptionPane.showMessageDialog(null, billMessage);
            } else {
                JOptionPane.showMessageDialog(null, "Failed to rent the motorbike. Please try again.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Customer with ID " + idcus + " not found.");
        }

        IDMotorbikeText.setText("");
        IDnumText.setText("");
        DesText.setText("");


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DesText;
    private javax.swing.JTextField IDMotorbikeText;
    private javax.swing.JTextField IDnumText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
